version: '3.6'
services:
  backend:
    hostname: backend
    build:
      context: .
    volumes:
      - './:/www'
    depends_on:
      - db
    ports:
      - '4000:4000'
    entrypoint: /bin/sh -c "cd /www && npm i && npm run start:dev"

  db:
    container_name: backend_dosug_postgres
    image: postgres:14
    environment:
      POSTGRES_DB: '${POSTGRES_DATABASE}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

    restart: unless-stopped

  admin_pgadmin:
    container_name: dosug_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${ADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${ADMIN_PASSWORD}'
      PGADMIN_CONFIG_SERVER_MODE: '${PROD_MODE}'
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped

  nginx:
    #    image: nginx:1.23-alpine
    build: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./:/www"
      - "./nginx/conf.d/development.conf:/etc/nginx/nginx.conf"
volumes:
  pgadmin:
  postgres:
